version: '3.8'

services:
  # Apache Solr Service
  solr:
    image: solr:9.4
    container_name: job-search-solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
      - ./solr-config:/opt/solr/server/solr/configsets/jobtitles:ro
    command:
      - solr-precreate
      - jobtitles
      - /opt/solr/server/solr/configsets/jobtitles
    environment:
      - SOLR_HEAP=512m
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8983/solr/jobtitles/admin/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - job-search-network

  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: job-search-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - job-search-network

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-search-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SOLR_BASE_URL=http://solr:8983/solr
      - SOLR_COLLECTION=jobtitles
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - job-search-network
    restart: unless-stopped

volumes:
  solr_data:
    driver: local
  redis_data:
    driver: local

networks:
  job-search-network:
    driver: bridge