# Docker-specific configuration
spring:
  application:
    name: job-title-search
  
  # Redis Configuration (Docker network)
  data:
    redis:
      host: redis
      port: 6379
      timeout: 5000
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
  
  # Cache Configuration
  cache:
    redis:
      time-to-live: 600000
  
  # JSON Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Server Configuration
server:
  port: 8080

# Solr Configuration (Docker network)
solr:
  base:
    url: http://solr:8983/solr
  collection: jobtitles
  connection:
    timeout: 15000
  request:
    timeout: 45000
  max:
    connections: 200

# Data Loader Configuration
data:
  loader:
    enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    ca.jobsearch: INFO
    org.apache.solr: WARN
    org.springframework.data.redis: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - caches
  endpoint:
    health:
      show-details: always