server:
  port: 8080
  compression:
    enabled: true

spring:
  application:
    name: job-search-engine

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 300000  # 5 minutes
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "job-search::"

  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Solr Configuration
solr:
  base:
    url: http://localhost:8983/solr
  collection: jobtitles
  connection:
    timeout: 10000
  request:
    timeout: 30000
  max:
    connections: 200

# Data Loader Configuration
data:
  loader:
    enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.bet99.exercise.jobsearch: DEBUG
    org.apache.solr: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always